version: '3.7'
services:
    db:
        image: postgres:10.7
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /var/lib/postgresql/data
        volumes:
            - pgdata:/var/lib/postgresql/data/

    nginx:
        build: ./nginx
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - webdata:/srv/www
            - ./log:/var/log/nginx
        depends_on:
            - web

    web:
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        build: ./web
        restart: always
        command: bash -c "poetry update --no-interaction --no-ansi && python manage.py db upgrade && uwsgi --ini uwsgi.ini"
        volumes:
            - webdata:/srv/www
        depends_on:
            - db

volumes:
    webdata:
    pgdata:


